source "http://rubygems.org"

# Specify your gem's dependencies in ubiquo_core.gemspec
gemspec

group :development, :test do
  path "../" do
  end

  gem 'calendar_date_select', :git => 'git://github.com/gnuine/calendar_date_select'
end
