source "http://rubygems.org"

# Specify your gem's dependencies in ubiquo_jobs.gemspec
gemspec

gem "ubiquo_core", :path => ".."
gem 'calendar_date_select', :git => 'git://github.com/gnuine/calendar_date_select'
