source "http://rubygems.org"

# Specify your gem's dependencies in ubiquo_media.gemspec
gemspec

# Using the git version to get 1.9.3 support
gem 'linecache19', :git => 'git://github.com/mark-moseley/linecache'

gem "ubiquo_core", :path => ".."
gem "routing-filter"
gem "pg"
gem "mysql2"