source "http://rubygems.org"

# Specify your gem's dependencies in ubiquo_design.gemspec
gemspec

path "../" do
  gem "ubiquo_core"
  gem "ubiquo_media"
  gem "ubiquo_authentication"
end

gem 'calendar_date_select', :git => 'git://github.com/gnuine/calendar_date_select'
