source "http://rubygems.org"

# Specify your gem's dependencies in ubiquo_core.gemspec
gemspec

# Using the git version to get 1.9.3 support
group :development, :test do
  gem 'linecache19', :git => 'git://github.com/mark-moseley/linecache'
  gem 'ruby-debug-base19x', '~> 0.11.30.pre4'
  gem 'ruby-debug19'
end
