source "http://rubygems.org"

gemspec

group :development, :test do
  path "../" do
    gem "ubiquo_core"
  end
  gem 'calendar_date_select', :git => 'git://github.com/gnuine/calendar_date_select'
end