# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ubiquo"
  s.version = "0.9.0.b9"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Albert Callarisa", "Jordi Beltran", "Bernat Foj", "Eric Garc\u{ed}a", "Felip Ladr\u{f3}n", "David Lozano", "Antoni Reina", "Ramon Salvad\u{f3}", "Arnau S\u{e1}nchez"]
  s.date = "2012-02-15"
  s.description = "This gem provides a command-line interface to speed up the creation of ubiquo based apps."
  s.email = "rsalvado@gnuine.com"
  s.executables = ["ubiquo"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".gitignore",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/ubiquo",
    "lib/ubiquo.rb",
    "lib/ubiquo/generator.rb",
    "lib/ubiquo/options.rb",
    "lib/ubiquo/template.erb",
    "test/fixtures/template.erb",
    "test/helper.rb",
    "test/ubiquo/generator_test.rb",
    "test/ubiquo/options_test.rb",
    "ubiquo.gemspec"
  ]
  s.homepage = "http://www.ubiquo.me"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "command line application for building ubiquo based applications."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 3.2.0.rc2"])
    else
      s.add_dependency(%q<rails>, ["~> 3.2.0.rc2"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 3.2.0.rc2"])
  end
end

